### ISSUE TITLE
'stroke' not defined

### ISSUE THREAD

**Issue by bradleybossard** [llimllib/pymag-trees#2]
Hello, sorry if I missed something obvious, but I get the following error below.  I don't see stroke defined in in the repo.  Do I need to use IPython or install a certain library?  I am using OSX.

python figure1.py 
Traceback (most recent call last):
  File "figure1.py", line 3, in <module>
    from buchheim import buchheim
  File "/Users/bradleybossard/gitsrc/pymag-trees/buchheim.py", line 163, in <module>
    stroke(0)
NameError: name 'stroke' is not defined

**Comment by Yamilquery** [comment]
Gracias, tenía el mismo problema, comentando dichas lineas se soluciono todo. :)

**Comment by llimllib** [comment]
I'm not maintaining this software any longer, if anybody wants to submit a PR I would gladly accept it.
