### ISSUE TITLE
How to use function `gentree`?

### ISSUE THREAD

**Issue by MrWater98** [llimllib/pymag-trees#6]
Thank you very much for this library. Now I would like to make it a API now, and it requires to generate a Tree object by passing parameters. I noticed that you offer a `gentree` function in 33 line of `gen.py`, how should I use this function correctly?

**Comment by llimllib** [comment]
Hi @MrWater98 , I don't know! This is just the code I used to make the demos in an article I wrote a decade ago so I'm not sure, to be honest

**Comment by MrWater98** [comment]
Well, I solved it by walking through the algorithm. Really appreciate to your great job~

**Comment by llimllib** [comment]
great! glad it was useful
