### ISSUE TITLE
Last listing don't match the script from the repo

### ISSUE THREAD

**Issue by vfarafonov** [llimllib/pymag-trees#9]
The last listing in the Github Pages article does not match the content [of the `buchheim.py` file](https://github.com/llimllib/pymag-trees/blob/master/buchheim.py#L132). 
For example:
- in the article the `second_walk` function does not have `min` param in the signature. But it is passed when the function is recursively invoked. Also, this function misses some other logic.
- there is no `third_walk` function and its usage in the listing. (I know that it could be excluded intentionally because it just shifts all items. Mentioning JIC)

P.S. Thanks for the article and the repo. This is very helpful even though the content was created a very long time ago! 🚀

**Comment by llimllib** [comment]
Thanks! glad you found it useful.

I wrote it 15 years ago so I don't exactly remember why that is - I've updated the code listing but I didn't check to see if it makes sense with the surrounding text 🤷‍♂️
